// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.leo.microservice.protobuf;

public interface CartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leo.microservice.cartservice.proto.CartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cartId = 1;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>double cartTotalPrice = 2;</code>
   * @return The cartTotalPrice.
   */
  double getCartTotalPrice();

  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartItemResponse cartItems = 3;</code>
   */
  java.util.List<com.leo.microservice.protobuf.CartItemResponse> 
      getCartItemsList();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartItemResponse cartItems = 3;</code>
   */
  com.leo.microservice.protobuf.CartItemResponse getCartItems(int index);
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartItemResponse cartItems = 3;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartItemResponse cartItems = 3;</code>
   */
  java.util.List<? extends com.leo.microservice.protobuf.CartItemResponseOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartItemResponse cartItems = 3;</code>
   */
  com.leo.microservice.protobuf.CartItemResponseOrBuilder getCartItemsOrBuilder(
      int index);
}
