// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.leo.microservice.protobuf;

public interface CartsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leo.microservice.cartservice.proto.CartsRequest)
    com.google.protobuf.MessageOrBuilder {
}
