// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.leo.microservice.protobuf;

public interface CartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leo.microservice.cartservice.proto.CartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cartId = 1;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>int64 productId = 2;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
