spring:
  data:
    mongodb:
      authentication-database: admin
      database: ${MONGO_DB_DATABASE:Loggertest}
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:localhost}
#      username: ${MONGODB_USER}
#      password: ${MONGODB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
server:
  port: '8092'
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        
