// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.leo.microservices.cartgatewayservice.protobuf;

public interface CartsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leo.microservice.cartservice.proto.CartsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartResponse carts = 1;</code>
   */
  java.util.List<com.leo.microservices.cartgatewayservice.protobuf.CartResponse> 
      getCartsList();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartResponse carts = 1;</code>
   */
  com.leo.microservices.cartgatewayservice.protobuf.CartResponse getCarts(int index);
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartResponse carts = 1;</code>
   */
  int getCartsCount();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartResponse carts = 1;</code>
   */
  java.util.List<? extends com.leo.microservices.cartgatewayservice.protobuf.CartResponseOrBuilder> 
      getCartsOrBuilderList();
  /**
   * <code>repeated .com.leo.microservice.cartservice.proto.CartResponse carts = 1;</code>
   */
  com.leo.microservices.cartgatewayservice.protobuf.CartResponseOrBuilder getCartsOrBuilder(
      int index);
}
